# Generated by Django 4.2.3 on 2023-11-16 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_practiceentry_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practiceentry',
            options={'ordering': ['-created']},
        ),
    ]
