# Generated by Django 4.2.3 on 2023-11-16 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '__first__'),
        ('student', '0004_alter_practiceentry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
