# Generated by Django 4.2.7 on 2023-11-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_user_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='student_or_teacher',
        ),
    ]
